admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

site_web:
    resource: "@SiteWebBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
